baseURL = "https://revanthp.github.io"
languageCode = "en-us"
title = "Revanth's blog"
theme = ["PaperMod"]
contentdir = "content"
publishdir = "public"
builddrafts = false
canonifyurls = true
paginate = 5
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = ["posts"]

[minify]
disableXML = true
# minifyOutput = true

[indexes]
category = "categories"
tag = "tags"

[params]
search_engine = true
env = "production"
description = "A place to store Revanth's notes."
author = ["Revanth Pentyala"]
defaultTheme = "auto"
# disableThemeToggle = true
ShowShareButtons = true
ShowReadingTime = true
# disableSpecial1stPost = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
# comments = false
# images = ["images/papermod-cover.png"]

[params.profileMode]
enabled = false
title = "PaperMod"
imageUrl = "#"
imageTitle = "my image"
# imageWidth = 120
# imageHeight = 120
buttons = [
    { name = "Posts", url = "posts" },
    { name = "Archives", url = "archives" },
    { name = "Tags", url = "tags" }
]

[params.homeInfoParams]
Title = "Revanth's Blog"
Content = """
👋 Welcome to demo page of Revanth's blog!
- This is designed to be a collection of my notes.
"""

[[params.socialIcons]]
name = "github"
title = "View Source on Github"

[security]
enableInlineShortcodes = false

[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]

[security.funcs]
getenv = ["^HUGO_"]

[security.http]
methods = ["(?i)GET|POST"]
urls = [".*"]

[markup]
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[languages.en]
languageName = "English"
weight = 1

[languages.en.taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[languages.en.menu.main]]
name = "Posts"
url = "posts"
weight = 5

[[languages.en.menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[[languages.en.menu.main]]
name = "WiKi"
url = "https://github.com/adityatelange/hugo-PaperMod/wiki/"

[outputs]
home = ["HTML", "RSS", "JSON"]