baseURL = "https://revanthp.github.io"
languageCode = "en-us"
title = "Revanth's blog"
theme = ["PaperMod"]
contentdir = "content"
publishdir = "public"
builddrafts = false
canonifyurls = true
paginate = 5
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = ["posts"]
enableGitInfo = true
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true

[services]
  [services.googleAnalytics]
    ID = "googlec454b1d57d24080d"

[[analytics.google]]
  SiteVerificationTag= "googlec454b1d57d24080d"

[minify]
disableXML = true
minifyOutput = true

[indexes]
category = "categories"
tag = "tags"

[params]
images = ["/favicon.ico"]
search_engine = true
env = "production"
description = "Revanth's personal blog about technology, programming, and more."
keywords = ["blog", "tech", "programming", "machine learning", "artificial intelligence"]
author = ["Revanth Pentyala"]
defaultTheme = "auto"
# disableThemeToggle = true
ShowShareButtons = true
ShowReadingTime = true
# disableSpecial1stPost = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
# comments = false
# images = ["images/papermod-cover.png"]

[params.profileMode]
enabled = false
title = "PaperMod"
imageUrl = "#"
imageTitle = "my image"
# imageWidth = 120
# imageHeight = 120
buttons = [
    { name = "Posts", url = "posts" },
    { name = "Archives", url = "archives" },
    { name = "Tags", url = "tags" }
]

[params.homeInfoParams]
Title = "Revanth's Blog"
Content = """
👋 Welcome to demo page of Revanth's blog!
- This is designed to be a collection of my notes.
"""

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"
safari_pinned_tab = "/safari-pinned-tab.svg"


[[params.socialIcons]]
name = "github"
title = "View Source on Github"
url = "https://github.com/revanthp"

[[params.socialIcons]]
name = "linkedin"
title = "Linkedin Profile"
url = "https://www.linkedin.com/in/revanthpentyala/"

[security]
enableInlineShortcodes = true

[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$", "^git$"]
osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]

[security.funcs]
getenv = ["^HUGO_"]

[security.http]
methods = ["(?i)GET|POST"]
urls = [".*"]

[markup]
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[languages.en]
languageName = "English"
weight = 1

[languages.en.taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[languages.en.menu.main]]
name = "Posts"
url = "posts"
weight = 1

[[languages.en.menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 20

# [[languages.en.menu.main]]
# name = "WiKi"
# url = "https://github.com/revanthp"

[outputs]
home = ["HTML", "RSS", "JSON"]

# for SEO and google search
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"

