baseURL = 'https://revanthp.github.io/'
languageCode = 'en-us'
title = "Revanth's blog"


theme = "PaperMod"
contentdir = "content"
publishdir = "public"
builddrafts = false
canonifyurls = true
paginate = 5

[indexes]
  category = "categories"
  tag = "tags"

[params]
  search_engine = true

[security]
enableInlineShortcodes = false

[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]

[security.funcs]
getenv = ["^HUGO_"]

[security.http]
methods = ["(?i)GET|POST"]
urls = [".*"]

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

